
name: build-mac

on:
  push:
    # branches: [ htmx-ting ]
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

          mkdir dist
          mkdir builds

      - name: Build
        run: |
          cargo build --release --target x86_64-apple-darwin
          mkdir builds/ramilang-macos-x86_64
          cp target/x86_64-apple-darwin/release/ramilang builds/ramilang-macos-x86_64
          tar -C builds -czvf dist/ramilang-macos-x86_64.tar.gz ramilang-macos-x86_64

          cargo build --release --target aarch64-apple-darwin
          mkdir builds/ramilang-macos-aarch64
          cp target/aarch64-apple-darwin/release/ramilang builds/ramilang-macos-aarch64
          tar -C builds -czvf dist/ramilang-macos-aarch64.tar.gz ramilang-macos-aarch64
        
      - name: Upload x86_64
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            dist/ramilang-macos-x86_64.tar.gz
            dist/ramilang-macos-aarch64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Upload x86_64
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #       upload_url: ${{ github.event.release.upload_url }}
      #       asset_path: dist/ramilang-macos-x86_64.tar.gz 
      #       asset_name: ramilang-macos-x86_64.tar.gz
      #       asset_content_type: application/gzip

      # - name: Upload aarch64
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #       upload_url: ${{ github.event.release.upload_url }}
      #       asset_path: dist/ramilang-macos-aarch64.tar.gz 
      #       asset_name: ramilang-macos-aarch64.tar.gz
      #       asset_content_type: application/gzip
