
name: build-mac

on:
  push:
    branches: [ htmx-ting ]
    # tags: ["v*.*.*"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install libdbus-1-dev pkg-config libudev-dev libglfw3-dev libglew-dev
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

          mkdir dist
          mkdir builds

      - name: Build
        run: |
          cargo build --release --target x86_64-apple-darwin
          cargo build --release --target aarch64-apple-darwin

      # - name: Upload
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #       upload_url: ${{ github.event.release.upload_url }}
      #       asset_path: ./bin/oq
      #       asset_name: oq-${{ github.event.release.tag_name }}-linux-x86_64
      #       asset_content_type: binary/octet-stream
